require 'rails_helper'

RSpec.describe "Api::Client::ScheduleActivities", type: :request do
  let!(:activity) { create(:activity) }
  let!(:schedule) { create(:schedule) }
  let!(:schedule_activity) { create(:schedule_activity, schedule: schedule, activity: activity) }

  path '/client/schedule_activities' do
    get 'List of schedules available' do
      tags %w[Clients Activities]
      security [bearerAuth: []]
      description 'List of activities scheduled available for a client'
      produces 'application/json'

      response '200', 'OK' do
        include_context 'generate client token'
        include_context 'autogenerated example'
      end

      response '403', 'Forbidden' do
        include_context 'generate admin token'
        include_context 'autogenerated example'
      end
    end
  end
end
