require 'rails_helper'

RSpec.describe "Api::Client::ScheduleActivities", type: :request do
  let!(:activity) { create(:activity) }
  let!(:schedule) { create(:schedule) }
  let!(:schedule_activity) { create(:schedule_activity, schedule: schedule, activity: activity) }

  path '/client/schedule_activities' do
    get 'List of schedules available' do
      tags %w[Clients Activities]
      security [bearerAuth: []]
      description 'List of activities booked by the client'
      produces 'application/json'

      response '200', 'OK' do
        include_context 'generate client token'
        include_context 'autogenerated example'
      end

      response '403', 'Forbidden' do
        include_context 'generate admin token'
        let!(:activity) { create(:activity) }
        let!(:schedule) { create(:schedule) }
        let!(:schedule_activity) { create(:schedule_activity, schedule: schedule, activity: activity) }
        let(:schedule_activity_user) { create(schedule_activity: schedule_activity, user: user) }
        include_context 'autogenerated example'
      end
    end
  end

  path '/client/schedule_activities/available' do
    get 'List of schedules available' do
      tags %w[Clients Activities]
      security [bearerAuth: []]
      description 'List of activities available to the client and that has not been booked by him/her. The activities already booked by the client, will not be shown'
      produces 'application/json'

      response '200', 'OK' do
        include_context 'generate client token'
        include_context 'autogenerated example'
      end

      response '403', 'Forbidden' do
        include_context 'generate admin token'
        include_context 'autogenerated example'
      end
    end
  end

  path '/client/schedule_activities/{id}/book' do
    parameter name: :id, in: :path, type: :string

    let!(:activity) { create(:activity) }
    let!(:schedule) { create(:schedule) }
    let!(:schedule_activity) { create(:schedule_activity, schedule: schedule, activity: activity) }
    let!(:id) { schedule_activity.id }

    post 'Book an activity' do
      tags 'Booking'
      description 'It books an activity to the user'
      security [bearerAuth: []]
      produces 'application/json'

      response '200', 'Activity booked' do
        include_context 'generate client token'
        include_context 'autogenerated example'
      end

      response '403', 'Forbidden' do
        include_context 'generate admin token'
        include_context 'autogenerated example'
      end
    end
  end
end
