---
swagger: '2.0'
info:
  title: API V1
  version: v1
basePath: "/api"
paths:
  "/admin/activities":
    post:
      summary: Creates a new activity
      tags:
      - Activities
      description: On this endpoint the admin is able to create a new activity
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: activity
        in: body
        schema:
          type: object
          properties:
            activity:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                mode:
                  type: string
                  enum:
                  - outdoor
                  - indoor
                  - virtual
              required:
              - name
              - mode
      responses:
        '201':
          description: New activity created
          examples:
            application/json:
              data:
                id: 126
                name: foo
                description: bar
                mode: outdoor
        '422':
          description: Missing properties or Invalid Values
          examples:
            application/json:
              error:
                type: Unprocessable entity
                message: Validation failed
                details:
                  name:
                  - can't be blank
    get:
      summary: List of activities
      tags:
      - Activities
      description: Shows a list of activities
      produces:
      - application/json
      responses:
        '200':
          description: List of Activities
          examples:
            application/json:
              data: []
  "/admin/activities/{id}":
    parameters:
    - name: id
      in: path
      type: string
      required: true
    patch:
      summary: Updates an activity
      tags:
      - Activities
      description: It updates requested fields from an specific activity
      consumes:
      - application/json
      parameters:
      - name: activity
        in: body
        schema:
          properties:
            activity:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                mode:
                  type: string
                  enum:
                  - outdoor
                  - indoor
                  - virtual
      responses:
        '200':
          description: Updated
          examples:
            application/json:
              data:
                id: 127
                name: new name
                description: Inventore quis soluta. Minima sunt omnis. Est dolor alias.
                mode: outdoor
        '404':
          description: Not found
          examples:
            application/json:
              error:
                type: Record not found
                message: Activity with id = 0 wasn't found
                details: {}
    get:
      summary: Get an specific activity
      tags:
      - Activities
      description: Shows an specific activity
      produces:
      - application/json
      responses:
        '200':
          description: Show activity
          examples:
            application/json:
              data:
                id: 129
                name: id
                description: Rerum id expedita. Nam ea aperiam. Praesentium animi
                  at.
                mode: virtual
                created_at: '2020-12-12T04:22:43.645Z'
                updated_at: '2020-12-12T04:22:43.645Z'
        '404':
          description: Not found
          examples:
            application/json:
              error:
                type: Record not found
                message: Activity with id = 0 wasn't found
                details: {}
  "/oauth/token":
    post:
      summary: Get access token
      tags:
      - OAuth
      description: Enter the username (email), password and grant type in order to
        get the access token, which will be necessary to access to the endpoints depending
        on the user role
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: auth
        in: body
        schema:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
            grant_type:
              type: string
              enum:
              - password
          required:
          - username
          - password
          - grant_type
      responses:
        '200':
          description: Get access token
          examples:
            application/json:
              access_token: q24agAUT4R0CVGSrfaQSSkJ1QsPbs-iZhotasI_-xlc
              token_type: Bearer
              expires_in: 7200
              refresh_token: XKSC-IzdPGUlsdJo8EA5Nry9El4134J82coFajIfHgY
              scope: public
              created_at: 1607746963
  "/users/register":
    post:
      summary: Register a user
      tags:
      - Users
      description: On this endpoint a new user can be registered. Once the user is
        registered successfully, use the /oauth/token endpoint to obtain an access
        token
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - first_name
              - last_name
              - email
              - password
      responses:
        '204':
          description: New user created
